use std::collections::HashMap;

pub struct ItemBinInfo {
    pub name: String,
    pub type_: i32,
    pub begin_index_32: i32,
    pub end_index_32: i32,
    pub begin_index_64: i32,
    pub end_index_64: i32,
    pub two_begin_index_32: i32,
    pub two_end_index_32: i32,
    pub link_file: Option<String>,
    pub remark: Option<String>,
    pub can_change: bool,
    pub data_length: Option<i32>,
    pub server_column: Option<String>,
}

pub fn init_item_bin_info() -> HashMap<&'static str, ItemBinInfo> {
    let mut item_bin_info = HashMap::new();
    item_bin_info.insert(
        "id",
        ItemBinInfo {
            name: "id".to_string(),
            type_: 0,
            begin_index_32: 0,
            end_index_32: 0,
            begin_index_64: 0,
            end_index_64: 0,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("编号".to_string()),
            can_change: true,
            data_length: Some(8),
            server_column: None,
        },
    );
    item_bin_info.insert(
        "alias",
        ItemBinInfo {
            name: "alias".to_string(),
            type_: 0,
            begin_index_32: 0,
            end_index_32: 0,
            begin_index_64: 0,
            end_index_64: 0,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("别名".to_string()),
            can_change: true,
            data_length: Some(0),
            server_column: None,
        },
    );
    item_bin_info.insert(
        "money-cost",
        ItemBinInfo {
            name: "money-cost".to_string(),
            type_: 0,
            begin_index_32: 40,
            end_index_32: 48,
            begin_index_64: 48,
            end_index_64: 56,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("金钱成本".to_string()),
            can_change: true,
            data_length: Some(8),
            server_column: Some("money-cost".to_string()),
        },
    );
    item_bin_info.insert(
        "consume-sub-ingredient",
        ItemBinInfo {
            name: "consume-sub-ingredient".to_string(),
            type_: 0,
            begin_index_32: 568,
            end_index_32: 570,
            begin_index_64: 576,
            end_index_64: 578,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("是否使用祭品".to_string()),
            can_change: true,
            data_length: Some(2),
            server_column: Some("consume-sub-ingredient".to_string()),
        },
    );
    item_bin_info.insert(
        "consume-fixed-ingredient",
        ItemBinInfo {
            name: "consume-fixed-ingredient".to_string(),
            type_: 0,
            begin_index_32: 736,
            end_index_32: 738,
            begin_index_64: 744,
            end_index_64: 746,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("是否使用材料".to_string()),
            can_change: true,
            data_length: Some(2),
            server_column: Some("consume-fixed-ingredient".to_string()),
        },
    );
    item_bin_info.insert(
        "warning",
        ItemBinInfo {
            name: "warning".to_string(),
            type_: 0,
            begin_index_32: 954,
            end_index_32: 956,
            begin_index_64: 962,
            end_index_64: 964,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("警告类型".to_string()),
            can_change: true,
            data_length: Some(2),
            server_column: Some("warning".to_string()),
        },
    );
    item_bin_info.insert(
        "sub-ingredient-1-type",
        ItemBinInfo {
            name: "sub-ingredient-1-type".to_string(),
            type_: 0,
            begin_index_32: 120,
            end_index_32: 122,
            begin_index_64: 128,
            end_index_64: 130,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("祭品1类型".to_string()),
            can_change: true,
            data_length: Some(2),
            server_column: Some("sub-ingredient-1-type".to_string()),
        },
    );
    item_bin_info.insert(
        "sub-ingredient-1",
        ItemBinInfo {
            name: "sub-ingredient-1".to_string(),
            type_: 0,
            begin_index_32: 128,
            end_index_32: 136,
            begin_index_64: 136,
            end_index_64: 144,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("祭品1".to_string()),
            can_change: true,
            data_length: Some(8),
            server_column: Some("sub-ingredient-1".to_string()),
        },
    );
    item_bin_info.insert(
        "sub-ingredient-state-1",
        ItemBinInfo {
            name: "sub-ingredient-state-1".to_string(),
            type_: 0,
            begin_index_32: 136,
            end_index_32: 138,
            begin_index_64: 144,
            end_index_64: 146,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("祭品1 是否使用".to_string()),
            can_change: true,
            data_length: Some(2),
            server_column: Some("sub-ingredient-state-1".to_string()),
        },
    );
    item_bin_info.insert(
        "sub-ingredient-condition-type-1",
        ItemBinInfo {
            name: "sub-ingredient-condition-type-1".to_string(),
            type_: 0,
            begin_index_32: 288,
            end_index_32: 290,
            begin_index_64: 296,
            end_index_64: 298,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("祭品1 条件类型".to_string()),
            can_change: true,
            data_length: Some(2),
            server_column: Some("sub-ingredient-condition-type-1".to_string()),
        },
    );
    item_bin_info.insert(
        "sub-ingredient-min-level-1",
        ItemBinInfo {
            name: "sub-ingredient-min-level-1".to_string(),
            type_: 0,
            begin_index_32: 302,
            end_index_32: 304,
            begin_index_64: 310,
            end_index_64: 312,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("祭品1 最小等级".to_string()),
            can_change: true,
            data_length: Some(2),
            server_column: Some("sub-ingredient-min-level-1".to_string()),
        },
    );
    item_bin_info.insert(
        "sub-ingredient-stack-count-1",
        ItemBinInfo {
            name: "sub-ingredient-stack-count-1".to_string(),
            type_: 0,
            begin_index_32: 316,
            end_index_32: 320,
            begin_index_64: 324,
            end_index_64: 328,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("祭品1 数量".to_string()),
            can_change: true,
            data_length: Some(4),
            server_column: Some("sub-ingredient-stack-count-1".to_string()),
        },
    );
    item_bin_info.insert(
        "sub-ingredient-title-name-1",
        ItemBinInfo {
            name: "sub-ingredient-title-name-1".to_string(),
            type_: 0,
            begin_index_32: 344,
            end_index_32: 352,
            begin_index_64: 352,
            end_index_64: 360,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: Some("datafile_327.xml".to_string()),
            remark: Some("祭品1 标题名".to_string()),
            can_change: true,
            data_length: Some(8),
            server_column: Some("sub-ingredient-title-name-1".to_string()),
        },
    );
    item_bin_info.insert(
        "sub-ingredient-title-item-1",
        ItemBinInfo {
            name: "sub-ingredient-title-item-1".to_string(),
            type_: 0,
            begin_index_32: 456,
            end_index_32: 464,
            begin_index_64: 464,
            end_index_64: 472,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: Some("datafile_159.xml".to_string()),
            remark: Some("祭品1 标题道具".to_string()),
            can_change: true,
            data_length: Some(8),
            server_column: Some("sub-ingredient-title-item-1".to_string()),
        },
    );
    item_bin_info.insert(
        "sub-ingredient-title-item-state-1",
        ItemBinInfo {
            name: "sub-ingredient-title-item-state-1".to_string(),
            type_: 0,
            begin_index_32: 464,
            end_index_32: 466,
            begin_index_64: 472,
            end_index_64: 474,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("祭品1 标题道具是否使用".to_string()),
            can_change: true,
            data_length: Some(2),
            server_column: Some("sub-ingredient-title-item-state-1".to_string()),
        },
    );
    item_bin_info.insert(
        "fixed-ingredient-1",
        ItemBinInfo {
            name: "fixed-ingredient-1".to_string(),
            type_: 0,
            begin_index_32: 576,
            end_index_32: 584,
            begin_index_64: 584,
            end_index_64: 592,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: Some("datafile_159.xml".to_string()),
            remark: Some("材料1".to_string()),
            can_change: true,
            data_length: Some(8),
            server_column: Some("fixed-ingredient-1".to_string()),
        },
    );
    item_bin_info.insert(
        "fixed-ingredient-state-1",
        ItemBinInfo {
            name: "fixed-ingredient-state-1".to_string(),
            type_: 0,
            begin_index_32: 584,
            end_index_32: 586,
            begin_index_64: 592,
            end_index_64: 594,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("材料1 状态".to_string()),
            can_change: true,
            data_length: Some(2),
            server_column: Some("fixed-ingredient-state-1".to_string()),
        },
    );
    item_bin_info.insert(
        "fixed-ingredient-2",
        ItemBinInfo {
            name: "fixed-ingredient-2".to_string(),
            type_: 0,
            begin_index_32: 592,
            end_index_32: 600,
            begin_index_64: 600,
            end_index_64: 608,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: Some("datafile_159.xml".to_string()),
            remark: Some("材料2".to_string()),
            can_change: true,
            data_length: Some(8),
            server_column: Some("fixed-ingredient-2".to_string()),
        },
    );
    item_bin_info.insert(
        "fixed-ingredient-state-2",
        ItemBinInfo {
            name: "fixed-ingredient-state-2".to_string(),
            type_: 0,
            begin_index_32: 600,
            end_index_32: 602,
            begin_index_64: 608,
            end_index_64: 610,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("材料2 状态".to_string()),
            can_change: true,
            data_length: Some(2),
            server_column: Some("fixed-ingredient-state-2".to_string()),
        },
    );
    item_bin_info.insert(
        "fixed-ingredient-3",
        ItemBinInfo {
            name: "fixed-ingredient-3".to_string(),
            type_: 0,
            begin_index_32: 608,
            end_index_32: 616,
            begin_index_64: 616,
            end_index_64: 624,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: Some("datafile_159.xml".to_string()),
            remark: Some("材料3".to_string()),
            can_change: true,
            data_length: Some(8),
            server_column: Some("fixed-ingredient-3".to_string()),
        },
    );
    item_bin_info.insert(
        "fixed-ingredient-state-3",
        ItemBinInfo {
            name: "fixed-ingredient-state-3".to_string(),
            type_: 0,
            begin_index_32: 616,
            end_index_32: 618,
            begin_index_64: 624,
            end_index_64: 626,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("材料3 状态".to_string()),
            can_change: true,
            data_length: Some(2),
            server_column: Some("fixed-ingredient-state-3".to_string()),
        },
    );
    item_bin_info.insert(
        "fixed-ingredient-4",
        ItemBinInfo {
            name: "fixed-ingredient-4".to_string(),
            type_: 0,
            begin_index_32: 624,
            end_index_32: 632,
            begin_index_64: 632,
            end_index_64: 640,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: Some("datafile_159.xml".to_string()),
            remark: Some("材料4".to_string()),
            can_change: true,
            data_length: Some(8),
            server_column: Some("fixed-ingredient-4".to_string()),
        },
    );
    item_bin_info.insert(
        "fixed-ingredient-state-4",
        ItemBinInfo {
            name: "fixed-ingredient-state-4".to_string(),
            type_: 0,
            begin_index_32: 632,
            end_index_32: 634,
            begin_index_64: 640,
            end_index_64: 642,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("材料4 状态".to_string()),
            can_change: true,
            data_length: Some(2),
            server_column: Some("fixed-ingredient-state-4".to_string()),
        },
    );
    item_bin_info.insert(
        "fixed-ingredient-5",
        ItemBinInfo {
            name: "fixed-ingredient-5".to_string(),
            type_: 0,
            begin_index_32: 640,
            end_index_32: 648,
            begin_index_64: 648,
            end_index_64: 656,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: Some("datafile_159.xml".to_string()),
            remark: Some("材料5".to_string()),
            can_change: true,
            data_length: Some(8),
            server_column: Some("fixed-ingredient-5".to_string()),
        },
    );
    item_bin_info.insert(
        "fixed-ingredient-state-5",
        ItemBinInfo {
            name: "fixed-ingredient-state-5".to_string(),
            type_: 0,
            begin_index_32: 648,
            end_index_32: 650,
            begin_index_64: 656,
            end_index_64: 658,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("材料5 状态".to_string()),
            can_change: true,
            data_length: Some(2),
            server_column: Some("fixed-ingredient-state-5".to_string()),
        },
    );
    item_bin_info.insert(
        "fixed-ingredient-6",
        ItemBinInfo {
            name: "fixed-ingredient-6".to_string(),
            type_: 0,
            begin_index_32: 656,
            end_index_32: 664,
            begin_index_64: 664,
            end_index_64: 672,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: Some("datafile_159.xml".to_string()),
            remark: Some("材料6".to_string()),
            can_change: true,
            data_length: Some(8),
            server_column: Some("fixed-ingredient-6".to_string()),
        },
    );
    item_bin_info.insert(
        "fixed-ingredient-state-6",
        ItemBinInfo {
            name: "fixed-ingredient-state-6".to_string(),
            type_: 0,
            begin_index_32: 664,
            end_index_32: 666,
            begin_index_64: 672,
            end_index_64: 674,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("材料6 状态".to_string()),
            can_change: true,
            data_length: Some(2),
            server_column: Some("fixed-ingredient-state-6".to_string()),
        },
    );
    item_bin_info.insert(
        "fixed-ingredient-7",
        ItemBinInfo {
            name: "fixed-ingredient-7".to_string(),
            type_: 0,
            begin_index_32: 672,
            end_index_32: 680,
            begin_index_64: 680,
            end_index_64: 688,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: Some("datafile_159.xml".to_string()),
            remark: Some("材料7".to_string()),
            can_change: true,
            data_length: Some(8),
            server_column: Some("fixed-ingredient-7".to_string()),
        },
    );
    item_bin_info.insert(
        "fixed-ingredient-state-7",
        ItemBinInfo {
            name: "fixed-ingredient-state-7".to_string(),
            type_: 0,
            begin_index_32: 680,
            end_index_32: 682,
            begin_index_64: 688,
            end_index_64: 690,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("材料7 状态".to_string()),
            can_change: true,
            data_length: Some(2),
            server_column: Some("fixed-ingredient-state-7".to_string()),
        },
    );
    item_bin_info.insert(
        "fixed-ingredient-8",
        ItemBinInfo {
            name: "fixed-ingredient-8".to_string(),
            type_: 0,
            begin_index_32: 688,
            end_index_32: 696,
            begin_index_64: 696,
            end_index_64: 704,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: Some("datafile_159.xml".to_string()),
            remark: Some("材料8".to_string()),
            can_change: true,
            data_length: Some(8),
            server_column: Some("fixed-ingredient-8".to_string()),
        },
    );
    item_bin_info.insert(
        "fixed-ingredient-state-8",
        ItemBinInfo {
            name: "fixed-ingredient-state-8".to_string(),
            type_: 0,
            begin_index_32: 696,
            end_index_32: 698,
            begin_index_64: 704,
            end_index_64: 706,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("材料8 状态".to_string()),
            can_change: true,
            data_length: Some(2),
            server_column: Some("fixed-ingredient-state-8".to_string()),
        },
    );
    item_bin_info.insert(
        "fixed-ingredient-stack-count-1",
        ItemBinInfo {
            name: "fixed-ingredient-stack-count-1".to_string(),
            type_: 0,
            begin_index_32: 704,
            end_index_32: 708,
            begin_index_64: 712,
            end_index_64: 716,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("材料1 数量".to_string()),
            can_change: true,
            data_length: Some(4),
            server_column: Some("fixed-ingredient-stack-count-1".to_string()),
        },
    );
    item_bin_info.insert(
        "fixed-ingredient-stack-count-2",
        ItemBinInfo {
            name: "fixed-ingredient-stack-count-2".to_string(),
            type_: 0,
            begin_index_32: 708,
            end_index_32: 712,
            begin_index_64: 716,
            end_index_64: 720,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("材料2 数量".to_string()),
            can_change: true,
            data_length: Some(4),
            server_column: Some("fixed-ingredient-stack-count-2".to_string()),
        },
    );
    item_bin_info.insert(
        "fixed-ingredient-stack-count-3",
        ItemBinInfo {
            name: "fixed-ingredient-stack-count-3".to_string(),
            type_: 0,
            begin_index_32: 712,
            end_index_32: 716,
            begin_index_64: 720,
            end_index_64: 724,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("材料3 数量".to_string()),
            can_change: true,
            data_length: Some(4),
            server_column: Some("fixed-ingredient-stack-count-3".to_string()),
        },
    );
    item_bin_info.insert(
        "fixed-ingredient-stack-count-4",
        ItemBinInfo {
            name: "fixed-ingredient-stack-count-4".to_string(),
            type_: 0,
            begin_index_32: 716,
            end_index_32: 720,
            begin_index_64: 724,
            end_index_64: 728,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("材料4 数量".to_string()),
            can_change: true,
            data_length: Some(4),
            server_column: Some("fixed-ingredient-stack-count-4".to_string()),
        },
    );
    item_bin_info.insert(
        "fixed-ingredient-stack-count-5",
        ItemBinInfo {
            name: "fixed-ingredient-stack-count-5".to_string(),
            type_: 0,
            begin_index_32: 720,
            end_index_32: 724,
            begin_index_64: 728,
            end_index_64: 732,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("材料5 数量".to_string()),
            can_change: true,
            data_length: Some(4),
            server_column: Some("fixed-ingredient-stack-count-5".to_string()),
        },
    );
    item_bin_info.insert(
        "fixed-ingredient-stack-count-6",
        ItemBinInfo {
            name: "fixed-ingredient-stack-count-6".to_string(),
            type_: 0,
            begin_index_32: 724,
            end_index_32: 728,
            begin_index_64: 732,
            end_index_64: 736,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("材料6 数量".to_string()),
            can_change: true,
            data_length: Some(4),
            server_column: Some("fixed-ingredient-stack-count-6".to_string()),
        },
    );
    item_bin_info.insert(
        "fixed-ingredient-stack-count-7",
        ItemBinInfo {
            name: "fixed-ingredient-stack-count-7".to_string(),
            type_: 0,
            begin_index_32: 728,
            end_index_32: 732,
            begin_index_64: 736,
            end_index_64: 740,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("材料7 数量".to_string()),
            can_change: true,
            data_length: Some(4),
            server_column: Some("fixed-ingredient-stack-count-7".to_string()),
        },
    );
    item_bin_info.insert(
        "fixed-ingredient-stack-count-8",
        ItemBinInfo {
            name: "fixed-ingredient-stack-count-8".to_string(),
            type_: 0,
            begin_index_32: 732,
            end_index_32: 736,
            begin_index_64: 740,
            end_index_64: 744,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("材料8 数量".to_string()),
            can_change: true,
            data_length: Some(4),
            server_column: Some("fixed-ingredient-stack-count-8".to_string()),
        },
    );
    item_bin_info.insert(
        "title-item",
        ItemBinInfo {
            name: "title-item".to_string(),
            type_: 0,
            begin_index_32: 864,
            end_index_32: 872,
            begin_index_64: 872,
            end_index_64: 880,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: Some("datafile_159.xml".to_string()),
            remark: Some("标题物品".to_string()),
            can_change: true,
            data_length: Some(8),
            server_column: Some("title-item".to_string()),
        },
    );
    item_bin_info.insert(
        "title-item-state",
        ItemBinInfo {
            name: "title-item-state".to_string(),
            type_: 0,
            begin_index_32: 872,
            end_index_32: 874,
            begin_index_64: 880,
            end_index_64: 882,
            two_begin_index_32: 0,
            two_end_index_32: 0,
            link_file: None,
            remark: Some("标题物品状态".to_string()),
            can_change: true,
            data_length: Some(2),
            server_column: Some("title-item-state".to_string()),
        },
    );
    item_bin_info
}
